#!/bin/sh

ls -hlA | awk '{if ($1 ~ /^d/){dir=dir " " $9 " "}else if($1 ~ /^-/){file=file " " $9 " "}} END {print "directory:";system("echo " dir "|xargs du -sh|sort -hr");print "file:";system("echo " file "|xargs du -sh|sort -hr");print "total:";system("du -sh|sed -e 's/[.]$/total/'")}'| awk '{if($1 ~ /[0-9]/){print "\t" $0}else{print $0}}'
